### ISSUE TITLE
直观看掩码预测效果

### ISSUE THREAD

**Issue by HaoqianSong** [amazon-science/c2f-seg#4]
如何将test_c2f_seg.py输出的掩码图像和原图像融合到一起，直观得看出掩码预测的效果，像介绍中展示的图像一样，如下图。
![1709263354908](https://github.com/amazon-science/c2f-seg/assets/99889442/1910d154-57d3-4e95-9017-15b5304ab3cf)

**Comment by JianxGao** [comment]
You should save the `pred_fm` in the function during inference with `img_id` and `anno_id` firstly
https://github.com/amazon-science/c2f-seg/blob/817d656281b92f7f3d457b0937501b5ad162ffcc/src/image_model.py#L315-L323
and then, use the code to visualize it (do not forget to change the path):
```python
import random
import os
import numpy as np
import cvbase as cvb
import cv2
from pycocotools.coco import COCO
import pycocotools.mask as mask_utils
import pdb
import copy
import matplotlib.pyplot as plt
from PIL import Image

def add_mask(mask,img, color1, color_mask=np.array([0, 0, 255]),line_width=1):
    mask = mask.astype(np.bool)
    contours, _ = cv2.findContours(mask.astype(np.uint8), cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE) 
    res = cv2.drawContours(img.copy(), contours, -1, color1, line_width)
    res[mask] = res[mask] * 0.7 + color_mask * 0.3
    return res

def random_color():
    levels = range(0,220,1)
    return tuple(random.choice(levels) for _ in range(3))

def polys_to_mask(polygons, height, width):
    rles = mask_utils.frPyObjects(polygons, height, width)
    rle = mask_utils.merge(rles)
    mask = mask_utils.decode(rle)
    return mask

def make_json_dict(imgs, anns):
    imgs_dict = {}
    anns_dict = {}
    for ann in anns:
        image_id = ann["image_id"]
        if not image_id in anns_dict:
            anns_dict[image_id] = []
            anns_dict[image_id].append(ann)
        else:
            anns_dict[image_id].append(ann)
    for img in imgs:
        image_id = img['id']
        imgs_dict[image_id] = img['file_name']
    return imgs_dict, anns_dict

base_img_path = "/home/ubuntu/data/Kins/testing/image_2"
base_ann_path = "/home/ubuntu/data/Kins/update_test_2020.json"

anns = cvb.load(base_ann_path)
imgs_info = anns['images']
anns_info = anns["annotations"]

imgs_dict, anns_dict = make_json_dict(imgs_info, anns_info)


for img_id in anns_dict.keys():
    anns = anns_dict[img_id]
    img_name = imgs_dict[img_id]

    img_path = os.path.join(base_img_path, img_name)
    img = cv2.imread(img_path, cv2.IMREAD_COLOR)

    height, width, _ = img.shape

    for i in range(len(anns)):
        mask_dir = os.path.join("/home/ubuntu/data/KINS_gt_prediction","{}_{}".format(img_id, i),"refine_fm.png")
        ours_fm = np.array(Image.open(mask_dir).convert("L"))
        ours_fm = (ours_fm==215)
        color1 = [random.randint(0,220),random.randint(0,220),random.randint(0,220)]
        color2 = np.array(color1)+35
        try:
            img = add_mask(ours_fm, img, color1, color2, 2)
        except:
            continue
    cv2.imwrite("img_with_mask.png", img)
```

**Comment by HaoqianSong** [comment]
mask_dir = os.path.join("/home/ubuntu/data/KINS_gt_prediction","{}_{}".format(img_id, i),"refine_fm.png")和上面的预测掩码保存命名不太相似，这个"{}_{}".format(img_id, i),"refine_fm.png"是什么命名规则？

之前的plt.imsave("{}/{}_{}_{}.png".format(save_dir, iteration, int(image_id.item()), int(anno_id.item())), to_plot)保存文件为类似32931_6598_2.png的图像。

**Comment by JianxGao** [comment]
refine_fm就是pred_fm，需要自己单独保存，i是anno_id。如果用现在保存的结果，就按照位置，把pred_fm取出来，把路径改成你存储的就可以。

**Comment by NHB123** [comment]
![result](https://github.com/user-attachments/assets/daa10f3f-77c1-4d2d-a79e-b3ceb2cb4774)
您好，上面是按照给定代码执行后的结果。掩膜和物体图像不对应的原因可能是Image_model.py中
image_id, anno_id= meta["img_id"], meta["anno_id"] # 语句1
与
mask_dir = os.path.join("/home/ubuntu/data/KINS_gt_prediction","{}_{}".format(img_id, i),"refine_fm.png") # 语句2
中的id不对应。语句2中的图像id来源于文件update_test_2020.json。请问应该如何修改呢？

**Comment by NHB123** [comment]
> ![result](https://private-user-images.githubusercontent.com/127387646/363919808-daa10f3f-77c1-4d2d-a79e-b3ceb2cb4774.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MzEyMzksIm5iZiI6MTcyNTQzMDkzOSwicGF0aCI6Ii8xMjczODc2NDYvMzYzOTE5ODA4LWRhYTEwZjNmLTc3YzEtNGQyZC1hNzllLWIzY2ViMmNiNDc3NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNFQwNjIyMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZDc3NDg2ZjIzNzg1MDUxYjE1Yzk5NWNhYTU4OWNlNTA3NWM0YjQzY2QxN2ExY2EwZDYzMThiYzc1MWM3ODE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1FOWltQs66Z-Us3QwEIPEfJ-nkjAARHogurdeGZbkEA) 您好，上面是按照给定代码执行后的结果。掩膜和物体图像不对应的原因可能是Image_model.py中 image_id, anno_id= meta["img_id"], meta["anno_id"] # 语句1 与 mask_dir = os.path.join("/home/ubuntu/data/KINS_gt_prediction","{}_{}".format(img_id, i),"refine_fm.png") # 语句2 中的id不对应。语句2中的图像id来源于文件update_test_2020.json。请问应该如何修改呢？

1.保存pred_fm
   def visualize(self, pred_vm, pred_fm, meta, mode, iteration):  
        pred_fm = pred_fm.squeeze()
        pred_vm = pred_vm.squeeze()
        gt_vm = meta["vm_no_crop"].squeeze()
        gt_fm = meta["fm_no_crop"].squeeze()
        # save pred_fm in specified place
        img_id, anno_id = meta["img_id"], meta["anno_id"]
        pred_fm_2 = pred_fm.cpu().numpy()
        save_dir = os.path.join(self.root_path, '{}_samples_3'.format(mode))    
        plt.imsave("{}/{}_{}.png".format(save_dir, int(img_id.item()), int(anno_id.item())), pred_fm_2)
2.修改路径
将base_ann_path = "/home/ubuntu/data/Kins/update_test_2020.json"中的json文件改为instances_val_upate.json即可，效果如下
![result_2](https://github.com/user-attachments/assets/6402bd21-510c-40d2-a48c-80b85cdbd153)
