### ISSUE TITLE
自己图像数据集的遮挡预测

### ISSUE THREAD

**Issue by HaoqianSong** [amazon-science/c2f-seg#5]
问题描述：替换了testing/image_2的测试输入图像，预测的掩码还是之前未替换图像的掩码，不是当前输入图像的预测掩码。

操作过程：看到测试时仅调用了数据集文件夹下instances_val_upate.json、kins_intersection.pkl、kins_intersection_list.txt三个文件，仅将kins_intersection_list.txt文件中的内容改为0_0   0_1    0_2，其他两个文件未改动，输入图像发生上述变动，为啥预测的掩码没有相应的改变，想问问我的问题出在了哪里？（目的：进行没有分割标签的图像遮挡预测，下面是相应的错做过程）

[问题描述.docx](https://github.com/amazon-science/c2f-seg/files/14821587/default.docx)

**Comment by JianxGao** [comment]
很抱歉，我不太看的明白你的描述，但是要正确得到结果需要保证image, bbox, visible mask都是对应同一个物体的，你可以check这些入手。

**Comment by HaoqianSong** [comment]
好吧，我仅修改了图像和kins_intersection_list.txt文件中的内容，这样的话就没法进行对任意图像进行分割和遮挡掩码预测，依赖于visible mask，或者说必须提供visible mask才能进行遮挡预测，本以为是单阶段算法，只需要图像就可以进行相应的推理，分割和预测遮挡。

**Comment by JianxGao** [comment]
这个工作侧重点是补全，所以没有专门的detector，你可以找一个强的detector先预测出来visible mask再补全。

**Comment by HaoqianSong** [comment]
好的，了解了，感谢~~！
