### ISSUE TITLE
/media/focus/T7 Shield/Train_Data/KINS/vq_train_list.txt not found.

### ISSUE THREAD

**Issue by FocusGZL** [amazon-science/c2f-seg#7]
非常感谢您的开源代码，我之前已经下载了KINS数据集，但是跑的时候出现 /media/focus/T7 Shield/Train_Data/KINS/vq_train_list.txt not found.这个txt文件是什么？是在你提供的数据下载链接里面吗？期待您的回复！！

**Comment by JianxiongGao** [comment]
It is in the .rar file: https://data.dgl.ai/dataset/C2F-Seg/KINS.tar. It is used for the training of the vq model in the first stage.

**Comment by FocusGZL** [comment]
> It is in the .rar file: https://data.dgl.ai/dataset/C2F-Seg/KINS.tar. It is used for the training of the vq model in the first stage.

非常感谢您的回复，但我还想知道关于fishbowl数据的信息，运行该数据时，出现[Errno 2] No such file or directory: '/media/focus/T7 Shield/Train_Data/Fishbowl/train_fish.pkl'，这种关于鱼的训练权重希望您可以提供一下？非常感谢！！！

**Comment by FocusGZL** [comment]
> It is in the .rar file: https://data.dgl.ai/dataset/C2F-Seg/KINS.tar. It is used for the training of the vq model in the first stage.

我可不可以直接拿下载好的数据去训练，一定要下载这种权重吗？正如上面提到的[Errno 2] No such file or directory: '/media/focus/T7 Shield/Train_Data/Fishbowl/train_fish.pkl
