### ISSUE TITLE
关于提前生成的Visible Mask

### ISSUE THREAD

**Issue by ZitengXue** [amazon-science/c2f-seg#9]
作者您好，我想问一下您使用之前工作生成的Visible Mask是保留了全部的预测还是只保留了和每个GT最匹配的Mask？谢谢！

**Comment by JianxGao** [comment]
你好，在算ap ar的时候，我用保留了全部的visible mask，然后用我们的模型预测所有的amodal mask，再用原模型的方法算metric。

**Comment by ZitengXue** [comment]
我明白了，非常感谢您的及时回复！
